In [1]:
!pip install -q transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 20.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.1/311.1 kB 25.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 45.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 51.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 31.6 MB/s eta 0:00:00


In [29]:
from transformers import AutoProcessor, Wav2Vec2Model
import torch
import librosa
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from torch import nn
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.utils import shuffle
from sklearn.preprocessing import scale
from torchsummary import summary
from matplotlib.font_manager import FontProperties

torch.__version__


'2.1.0+cu118'

In [3]:
#加载模型
processor = AutoProcessor.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base-960h")

# 加载音频文件
audio_input, rate = librosa.load("test.wav", sr = 16000)

inputs = processor(audio_input, sampling_rate=16000, return_tensors="pt")

Some weights of Wav2Vec2Model were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [4]:

with torch.no_grad():
    outputs = model(**inputs)

last_hidden_states = outputs.last_hidden_state
print(last_hidden_states)
list(last_hidden_states.shape)


tensor([[[ 0.0184,  0.0249, -0.0534,  ..., -0.1300,  0.0519,  0.1058],
         [-0.0644,  0.0021, -0.0993,  ..., -0.2256,  0.0159,  0.1310],
         [-0.0644,  0.0021, -0.0993,  ..., -0.2255,  0.0159,  0.1310],
         ...,
         [-0.0071,  0.0287, -0.0498,  ..., -0.1711,  0.0360,  0.1172],
         [-0.0186,  0.0125, -0.0654,  ..., -0.1694,  0.0417,  0.1313],
         [-0.0159,  0.0108, -0.0674,  ..., -0.1684,  0.0438,  0.1396]]])


[1, 171, 768]

In [5]:
jawopen = [
            0.009586737491190434,
            0.008979345671832561,
            0.011321083642542362,
            0.010439089499413967,
            0.009360973723232746,
            0.006232088897377253,
            0.004848846234381199,
            0.009360488504171371,
            0.013829204253852367,
            0.017454467713832855,
            0.0196081455796957,
            0.04048984497785568,
            0.07197241485118866,
            0.06341962516307831,
            0.052364006638526917,
            0.013461578637361526,
            0.011079512536525726,
            0.006322343833744526,
            0.004936319775879383,
            0.005036789923906326,
            0.004498274996876717,
            0.004021129570901394,
            0.0048559606075286865,
            0.005624715238809586,
            0.005461822263896465,
            0.006910244934260845,
            0.004959948360919952,
            0.007502279244363308,
            0.009119633585214615,
            0.013383540324866772,
            0.02590612694621086,
            0.01770544797182083,
            0.00786164402961731,
            0.010478793643414974,
            0.027493944391608238,
            0.08369234949350357,
            0.11772142350673676,
            0.0706266537308693,
            0.015011589042842388,
            0.006985705345869064,
            0.0074021099135279655,
            0.006355965044349432,
            0.00825462769716978,
            0.012373908422887325,
            0.009418923407793045,
            0.009582826867699623,
            0.008861105889081955,
            0.004849016200751066,
            0.010531198233366013,
            0.009303479455411434,
            0.008775768801569939,
            0.006546579767018557,
            0.0034988783299922943,
            0.0034243701957166195,
            0.004655267111957073,
            0.005182082299143076,
            0.005518872756510973,
            0.006342220585793257,
            0.009763234294950962,
            0.0068406276404857635,
            0.0052495053969323635,
            0.00584684731438756,
            0.010323402471840382,
            0.027268482372164726,
            0.03300449624657631,
            0.01794753596186638,
            0.010961898602545261,
            0.005985470954328775,
            0.00395447202026844,
            0.0030053944792598486,
            0.0024215253069996834,
            0.002878825878724456,
            0.002389328321442008,
            0.002357768826186657,
            0.002324940636754036,
            0.0021527810022234917,
            0.004213900770992041,
            0.0046121045015752316,
            0.005094058811664581,
            0.006326064933091402,
            0.005623629782348871,
            0.005182364955544472,
            0.005025811493396759
        ]

# 将 Python 列表转换为 NumPy 数组
my_array = np.array(jawopen)

# 现在，my_array 是一个 NumPy 数组
print(my_array)
print(my_array.shape)

[0.00958674 0.00897935 0.01132108 0.01043909 0.00936097 0.00623209
 0.00484885 0.00936049 0.0138292  0.01745447 0.01960815 0.04048984
 0.07197241 0.06341963 0.05236401 0.01346158 0.01107951 0.00632234
 0.00493632 0.00503679 0.00449827 0.00402113 0.00485596 0.00562472
 0.00546182 0.00691024 0.00495995 0.00750228 0.00911963 0.01338354
 0.02590613 0.01770545 0.00786164 0.01047879 0.02749394 0.08369235
 0.11772142 0.07062665 0.01501159 0.00698571 0.00740211 0.00635597
 0.00825463 0.01237391 0.00941892 0.00958283 0.00886111 0.00484902
 0.0105312  0.00930348 0.00877577 0.00654658 0.00349888 0.00342437
 0.00465527 0.00518208 0.00551887 0.00634222 0.00976323 0.00684063
 0.00524951 0.00584685 0.0103234  0.02726848 0.0330045  0.01794754
 0.0109619  0.00598547 0.00395447 0.00300539 0.00242153 0.00287883
 0.00238933 0.00235777 0.00232494 0.00215278 0.0042139  0.0046121
 0.00509406 0.00632606 0.00562363 0.00518236 0.00502581]
(83,)


In [6]:
last_hidden_states = torch.tensor(last_hidden_states)  # 将列表转换为张量
jawopen = torch.tensor(jawopen)  # 将列表转换为张量



# 使用切片进行降采样
downsampled_last_hidden_states = last_hidden_states[:, ::2, :]

downsampled_last_hidden_states.shape

# 删除最后三个元素
downsampled_last_hidden_states = downsampled_last_hidden_states[:, :-3, :]

# 删除最后三个元素
downsampled_last_hidden_states.shape



# downsampled_last_hidden_states 现在具有与 jawopen 相匹配的帧数

<ipython-input-6-a5b1b24fdf07>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  last_hidden_states = torch.tensor(last_hidden_states)  # 将列表转换为张量


torch.Size([1, 83, 768])

In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
# 重塑 x 和 y 的形状以适应线性回归
x_reshaped = downsampled_last_hidden_states.reshape(-1, 768)
y_reshaped = jawopen.reshape(-1, 1)

print(x_reshaped.shape)
print(x_reshaped)
print(y_reshaped.shape)
print(y_reshaped)

# 划分数据集为训练集和测试集
x_train, x_test, y_train, y_test = train_test_split(x_reshaped, y_reshaped, test_size=0.2, random_state=42)

# 创建线性回归模型
regression_model = LinearRegression()

# 训练线性回归模型
regression_model.fit(x_train, y_train)

# 进行预测
y_pred = regression_model.predict(x_test)

# 计算均方误差（MSE）作为回归任务的评估指标
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error (MSE) on the test set: {mse}")

torch.Size([83, 768])
tensor([[ 0.0184,  0.0249, -0.0534,  ..., -0.1300,  0.0519,  0.1058],
        [-0.0644,  0.0021, -0.0993,  ..., -0.2255,  0.0159,  0.1310],
        [-0.0644,  0.0021, -0.0993,  ..., -0.2256,  0.0158,  0.1310],
        ...,
        [-0.0644,  0.0021, -0.0993,  ..., -0.2255,  0.0159,  0.1310],
        [-0.0067,  0.0254, -0.0543,  ..., -0.1658,  0.0385,  0.1283],
        [-0.0012,  0.0379, -0.0554,  ..., -0.1630,  0.0375,  0.1130]])
torch.Size([83, 1])
tensor([[0.0096],
        [0.0090],
        [0.0113],
        [0.0104],
        [0.0094],
        [0.0062],
        [0.0048],
        [0.0094],
        [0.0138],
        [0.0175],
        [0.0196],
        [0.0405],
        [0.0720],
        [0.0634],
        [0.0524],
        [0.0135],
        [0.0111],
        [0.0063],
        [0.0049],
        [0.0050],
        [0.0045],
        [0.0040],
        [0.0049],
        [0.0056],
        [0.0055],
        [0.0069],
        [0.0050],
        [0.0075],
        [0.0091],
  

In [20]:
print(y_pred.shape)
print(y_pred)


(17, 1)
[[-0.63841295]
 [-0.4173298 ]
 [-0.64848566]
 [ 0.9359231 ]
 [ 0.01497281]
 [-0.02761388]
 [ 0.06403399]
 [-0.86188626]
 [-0.16345656]
 [ 0.36883712]
 [ 0.12831187]
 [ 0.8802986 ]
 [ 1.279058  ]
 [ 0.5686691 ]
 [-0.8637111 ]
 [ 0.51157784]
 [-0.05655253]]
tensor([[-0.6384],
        [-0.4173],
        [-0.6485],
        [ 0.9359],
        [ 0.0150],
        [-0.0276],
        [ 0.0640],
        [-0.8619],
        [-0.1635],
        [ 0.3688],
        [ 0.1283],
        [ 0.8803],
        [ 1.2791],
        [ 0.5687],
        [-0.8637],
        [ 0.5116],
        [-0.0566]])


In [22]:
from sklearn.metrics import r2_score

# 计算 R²
r_squared = r2_score(y_test, y_pred)

r_squared

-711.2346732617685